# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: demarey/pharo-setup-gha@main
        with:
          version: 13

      - name: Create Folder
        run: |
          export MY_FOLDER="/tmp/Jean-Gaël Névès.09554bf2-eae7-0d00-9083-75440bec0189"
          mkdir "$MY_FOLDER"
          cp Pharo.image "$MY_FOLDER"
          cp Pharo.image "$MY_FOLDER"/Pharo2.image

      - name: Run Pharo
        run: |
          $PHARO --headless Pharo.image eval 'SystemVersion current printString'
          $PHARO --headless Pharo.image eval "'/tmp/Jean-Gaël Névès.09554bf2-eae7-0d00-9083-75440bec0189' asFileReference ensureDeleteAll"
